#!/bin/sh

case "$1" in
start)
    cd /lib/modules/5.15.18/extra
    echo "Loading scull module"
    /usr/bin/scull_load
    echo "Loading faulty module"
    /usr/bin/module_load faulty
    echo "Loading hello module"
    modprobe hello
    ;;
stop)
    cd /lib/modules/5.15.18/extra
    echo "Unloading scull module"
    /usr/bin/scull_unload
    echo "Unloading faulty module"
    /usr/bin/module_unload faulty
    echo "Unloading hello module"
    rmmod hello
    ;;
*)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
